apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-docker
  template:
    metadata:
      labels:
        app: express-docker
    spec:
      containers:
        - name: express-docker-container
          image: vaishnaviwohlig/express-docker:latest
