# name: Github Actions Automated

# on:
#   push:
#     branches: [ "main" ]
    
# jobs:
#   build_and_push :
#     name: Build committed code and push to dockerhub
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Checkout of repo
      
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         # uses: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#         with:
#           username: ${{secrets.DOCKER_USERNAME}}
#           password: ${{secrets.DOCKER_PASSWORD}}

#       # - name: Check tags
#       #   id: meta
#       #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#       #   with:
#       #     image: vaishnaviwohlig/express-docker

#       - name: Build and push to docker hub
#         # run: docker build -t vaishnaviwohlig/express-docker .
#         #      docker push vaishnaviwohlig/express-docker
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: true
#           tags: vaishnaviwohlig/express-docker:latest
#         #   label: ${{steps.meta.outputs.labels}}


name: Github Actions Automated

on:
  push:
    branches: [ "main" ]
    
jobs:
  build_and_push:
    name: Build committed code and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        # uses: docker/login-action@v2
        run: |
          echo "Dildosti@2512" | docker login -u vaishnaviwohlig --password-stdin

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: vaishnaviwohlig/express-docker:latest

        
          

      
        
        
      
    
    
    
  
